### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by BobWall23**

### CODE REVIEW

**Review by ernieturner — CHANGES_REQUESTED** [review]
Kinda seems like the `package.json` file should have been part of this commit too? I don't really know what it means to change the lock file without having any changes in the actual depdencies.

**Comment by BobWall23** [comment]
I did a `npm audit fix`, which didn't update the versions of any of the direct dependencies, but did update downstream dependencies.

It looks like the `package.json` file referenced `"@ironcorelabs/ironweb": "2.0.1"`, but `package-lock.json` did not, so maybe the `package-lock.json` didn't get checked in on the last update?

**Comment by ernieturner** [comment]
Always a possibility, I haven't had much involvement in this repo in quite a while. Just so you're aware, you can also run `yarn why lodash` to figure out which one of our dependencies has lodash as a dep, in case we can fix this directly instead of using the sub-dep fix.

**Review by ernieturner — APPROVED** [review]

**Comment by BobWall23** [comment]
I didn't extensively test - just did a quick runthrough. I'll just close those and someone can update in the future.

**Comment by ernieturner** [comment]
I'm confused, if you did a run through and things looked ok it's probably good enough to merge isn't it?

**Pull request closed without merging**
